"""
Safety and Compliance Layer for Healthcare Content
"""

import re
from typing import List

from schemas import DocumentType


class SafetyFilter:
    """
    Post-generation safety filters to ensure compliance.
    
    Filters:
    - Block diagnosis language
    - Block medication and dosage patterns
    - Block fitness/unfitness statements
    - Avoid absolute medical claims
    - Append healthcare disclaimers
    """
    
    def __init__(self):
        # Patterns that indicate diagnosis (to be flagged/blocked)
        self.diagnosis_patterns = [
            r'\b(diagnosed with|diagnosis of|diagnosed as)\b',
            r'\b(you have|patient has|confirmed)\s+\w+\s+(disease|disorder|syndrome|condition)\b',
            r'\b(positive for|negative for)\s+\w+\b',
            r'\b(suffering from|afflicted with)\b',
        ]
        
        # Medication and dosage patterns
        self.medication_patterns = [
            r'\b\d+\s*(mg|ml|mcg|g|IU)\b',  # Dosages
            r'\b(take|administer|prescribe[ds]?)\s+\d+\b',
            r'\b(twice|three times|once)\s+(daily|a day|per day)\b',
            r'\b(morning|evening|bedtime)\s+dose\b',
            r'\b(tablet[s]?|capsule[s]?|injection[s]?|drops)\s+of\b',
            r'\bprescription:\s*\w+\b',
        ]
        
        # Fitness/unfitness determination patterns
        self.fitness_patterns = [
            r'\b(fit for|unfit for|fit to|unfit to)\s+(work|duty|travel)\b',
            r'\b(cleared for|not cleared for)\b',
            r'\b(able to|unable to)\s+(work|perform|resume)\b',
            r'\b(medically fit|medically unfit)\b',
            r'\b(return to work|return to duty)\b',
        ]
        
        # Absolute claim patterns
        self.absolute_patterns = [
            r'\b(will cure|will heal|guaranteed|100%)\b',
            r'\b(always works|never fails)\b',
            r'\b(definitely|certainly)\s+(cure|treat|heal)\b',
        ]
        
        # Standard healthcare disclaimer
        self.standard_disclaimer = """
───────────────────────────────────────────────────
📋 HEALTHCARE DISCLAIMER

This document is generated by an AI system for informational and educational purposes only.

• This is NOT a substitute for professional medical advice, diagnosis, or treatment
• Always seek the advice of qualified healthcare providers
• Never disregard professional medical advice because of this content
• If you have a medical emergency, contact emergency services immediately

Generated by Healthcare GenAI SaaS
───────────────────────────────────────────────────"""
        
        # Medical Certificate specific disclaimer
        self.mc_disclaimer = """
═══════════════════════════════════════════════════
🏥 DRAFT DOCUMENT - NOT VALID FOR OFFICIAL USE

This Medical Certificate DRAFT:
• Requires review and signature by a licensed clinician
• Contains NO diagnosis or treatment information
• Makes NO fitness/unfitness determination
• Is NOT valid until officially signed and stamped

CLINICIAN REVIEW AND SIGNATURE REQUIRED
═══════════════════════════════════════════════════"""
    
    def filter(self, text: str, document_type: DocumentType) -> str:
        """
        Apply safety filters to generated text.
        
        Args:
            text: Generated text to filter
            document_type: Type of document for context-specific filtering
        
        Returns:
            Filtered and safe text
        """
        filtered_text = text
        
        # Apply filters based on document type
        if document_type == DocumentType.MEDICAL_CERTIFICATE:
            filtered_text = self._filter_medical_certificate(filtered_text)
        else:
            filtered_text = self._filter_general_content(filtered_text)
        
        # Ensure disclaimer is present
        filtered_text = self._ensure_disclaimer(filtered_text, document_type)
        
        return filtered_text
    
    def _filter_medical_certificate(self, text: str) -> str:
        """Apply strict filters for Medical Certificate"""
        result = text
        
        # Check and redact diagnosis patterns
        for pattern in self.diagnosis_patterns:
            result = re.sub(
                pattern,
                '[REMOVED - DIAGNOSIS NOT PERMITTED IN DRAFT]',
                result,
                flags=re.IGNORECASE
            )
        
        # Check and redact medication patterns
        for pattern in self.medication_patterns:
            result = re.sub(
                pattern,
                '[REMOVED - MEDICATION DETAILS NOT PERMITTED]',
                result,
                flags=re.IGNORECASE
            )
        
        # Check and redact fitness determination patterns
        for pattern in self.fitness_patterns:
            result = re.sub(
                pattern,
                '[TO BE DETERMINED BY CLINICIAN]',
                result,
                flags=re.IGNORECASE
            )
        
        return result
    
    def _filter_general_content(self, text: str) -> str:
        """Apply filters for general educational content"""
        result = text
        
        # Soften absolute claims
        for pattern in self.absolute_patterns:
            result = re.sub(
                pattern,
                'may help with',
                result,
                flags=re.IGNORECASE
            )
        
        # Add qualifiers to strong medical statements
        result = self._add_qualifiers(result)
        
        return result
    
    def _add_qualifiers(self, text: str) -> str:
        """Add appropriate qualifiers to medical statements"""
        # Add "generally" or "typically" to categorical statements
        patterns_to_qualify = [
            (r'\b(treatment is)\b', 'treatment is generally'),
            (r'\b(symptoms include)\b', 'symptoms may include'),
            (r'\b(causes are)\b', 'potential causes may include'),
            (r'\b(you should)\b', 'you may want to consider'),
            (r'\b(you must)\b', 'it is recommended to'),
        ]
        
        result = text
        for pattern, replacement in patterns_to_qualify:
            # Only replace if not already qualified
            result = re.sub(
                pattern,
                replacement,
                result,
                flags=re.IGNORECASE
            )
        
        return result
    
    def _ensure_disclaimer(self, text: str, document_type: DocumentType) -> str:
        """Ensure appropriate disclaimer is present"""
        
        # Check if disclaimer already exists
        if "DISCLAIMER" in text.upper() and "HEALTHCARE" in text.upper():
            return text
        
        # Add appropriate disclaimer
        if document_type == DocumentType.MEDICAL_CERTIFICATE:
            if "CLINICIAN REVIEW" not in text.upper():
                return text + "\n" + self.mc_disclaimer
        else:
            return text + "\n" + self.standard_disclaimer
        
        return text
    
    def validate(self, text: str, document_type: DocumentType) -> dict:
        """
        Validate text for compliance without modifying it.
        Returns validation results with any issues found.
        """
        issues = []
        
        # Check for diagnosis patterns
        for pattern in self.diagnosis_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                issues.append({
                    "type": "diagnosis",
                    "severity": "high",
                    "message": "Contains potential diagnosis language",
                    "matches": matches
                })
        
        # Check for medication patterns
        for pattern in self.medication_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                issues.append({
                    "type": "medication",
                    "severity": "high",
                    "message": "Contains medication or dosage information",
                    "matches": matches
                })
        
        # Check for fitness patterns (critical for Medical Certificate)
        if document_type == DocumentType.MEDICAL_CERTIFICATE:
            for pattern in self.fitness_patterns:
                matches = re.findall(pattern, text, re.IGNORECASE)
                if matches:
                    issues.append({
                        "type": "fitness_determination",
                        "severity": "critical",
                        "message": "Contains fitness/unfitness determination",
                        "matches": matches
                    })
        
        # Check for absolute claims
        for pattern in self.absolute_patterns:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                issues.append({
                    "type": "absolute_claim",
                    "severity": "medium",
                    "message": "Contains absolute medical claims",
                    "matches": matches
                })
        
        # Check for disclaimer
        has_disclaimer = "disclaimer" in text.lower()
        
        return {
            "is_valid": len(issues) == 0,
            "has_disclaimer": has_disclaimer,
            "issues": issues,
            "issue_count": len(issues)
        }
